// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzrxBkEOcd4MC2IJXbH70uKqbNKTPHAWU',
    appId: '1:647812089157:web:2ed20183866e50d0d3ea2c',
    messagingSenderId: '647812089157',
    projectId: 'test-54e68',
    authDomain: 'test-54e68.firebaseapp.com',
    databaseURL: 'https://test-54e68-default-rtdb.firebaseio.com',
    storageBucket: 'test-54e68.appspot.com',
    measurementId: 'G-T2VZ0SKLFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqHT6AhbyAu9MwbxjPfzXTcaqrU1_0LZk',
    appId: '1:647812089157:android:965f0d69b72f3e49d3ea2c',
    messagingSenderId: '647812089157',
    projectId: 'test-54e68',
    databaseURL: 'https://test-54e68-default-rtdb.firebaseio.com',
    storageBucket: 'test-54e68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUWXdlQtTxFk_yQcFU3cELhl40W9pFvzs',
    appId: '1:647812089157:ios:4b13b50d145ab466d3ea2c',
    messagingSenderId: '647812089157',
    projectId: 'test-54e68',
    databaseURL: 'https://test-54e68-default-rtdb.firebaseio.com',
    storageBucket: 'test-54e68.appspot.com',
    iosBundleId: 'com.example.poppinroadcimema',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUWXdlQtTxFk_yQcFU3cELhl40W9pFvzs',
    appId: '1:647812089157:ios:1e5dab7eee43f046d3ea2c',
    messagingSenderId: '647812089157',
    projectId: 'test-54e68',
    databaseURL: 'https://test-54e68-default-rtdb.firebaseio.com',
    storageBucket: 'test-54e68.appspot.com',
    iosBundleId: 'com.example.poppinroadcimema.RunnerTests',
  );
}
